arkestrator/board/urls.py
from django.conf.urls import url

from arkestrator.board import views
from arkestrator.board import models

urlpatterns = [
    url(r"^$",views.ThreadList.as_view(), name='list-threads'),
    url(r"^threads/(?P<id>\d+)/$",views.view_thread,name='view-thread'),
    url(r"^threads/(?P<id>\d+)/(?P<start>\d+)/$",views.view_thread,
        name='view-thread-start'),
    url(r"^threads/(?P<id>\d+)/full/$",views.view_thread,{
        'expand' : True,
    }, name='view-thread-full'),
    url(r"^threads/(?P<id>\d+)/(?P<start>\d+)/full/$",views.view_thread,{
        'expand' : True,
    }, name='view-thread-full-start'),
    url(r"^threads/(?P<id>\d+)/(?P<start>\d+)/full/show/$",views.view_thread,{
        'expand' : True, 'hide' : False,
    }, name='view-thread-full-show'),
    url(r"^threads/(?P<id>\d+)/(?P<start>\d+)/full/hide/$",views.view_thread,{
        'expand' : True, 'hide' : True,
    }, name='view-thread-full-hide'),
    url(r"^threads/(?P<id>\d+)/(?P<start>\d+)/hide/$",views.view_thread,{
        'expand' : False, 'hide' : True,
    }, name='view-thread-hide'),
    url(r"^threads/(?P<id>\d+)/(?P<start>\d+)/show/$",views.view_thread,{
        'expand' : False, 'hide' : False,
    }, name='view-thread-show'),
    url(r"^threads/(?P<id>\d+)/sticky/$",views.sticky,
        name='sticky'),
    url(r"^threads/(?P<id>\d+)/lock/$",views.lock_thread,
        name='lock-thread'),
    url(r"^threads/(?P<id>\d+)/history/$",views.thread_history,
        name='thread-history'),
    url(r"^threads/new/$",views.new_thread,name='new-thread'),
    url(r"^threads/mark_read/$",views.mark_read,name='mark-threads-read'),
    url(r"^profiles/(?P<by>\d+)/threads/$", views.ThreadsByList.as_view(),
            name='threads-by'),
    url(r"^profiles/(?P<id>\d+)/posts/$", views.PostsByListView.as_view(),
            name='posts-by'),
    url(r"^posts/(?P<id>\d+)/$",views.view_post,name='view-post'),
    url(r"^quote/(?P<id>\d+)/$", views.get_quote, name='get-quote'),
    url(r"^threads/(?P<id>\d+)/favorite/$", views.favorite_thread,
        name='favorite'),
    url(r"^threads/favorites/$", views.FavoritesList.as_view(),
            { 'fav' : True }, name='favorite-list'),
    url(r"^threads/search/$", views.ThreadTitleSearchView.as_view(), name='search-threads'),
]

arkestrator/urls.py
from django.conf.urls import include, url
from django.conf import settings
import django.views.static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from arkestrator.board.views import get_quote
from arkestrator.util.views import active_users

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)/$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^themes/', include('arkestrator.themes.urls')),
    url(r'', include('arkestrator.board.urls')),
    url(r'^profiles/', include('arkestrator.profiles.urls')),
    url(r'^invites/', include('arkestrator.invites.urls')),
    url(r'^pms/', include('arkestrator.pms.urls')),
    url(r'^events/', include('arkestrator.events.urls')),
    url(r'^gallery/', include('arkestrator.gallery.urls')),
    url(r'^mod/', include('arkestrator.moderation.urls')),
    url(r'^active/$', active_users, name='active-users'),
    url(r'^quote/(?P<id>\d+)/$', get_quote, name='get-quote'),
]

arkestrator/board/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.core.cache import cache
from django.core.urlresolvers import reverse

from arkestrator.decorators import instance_memcache
from bbking.fields import BBCodeField

import datetime


class Thread(models.Model):
    """ a Thread """

    class Meta:
        permissions=(
            ('can_sticky', 'Can sticky threads'),
            ('can_lock', 'Can lock threads'),
            )

    subject = models.CharField(max_length=160, blank=False)
    creator = models.ForeignKey(User,null=False,related_name='threads')
    last_post = models.ForeignKey("board.Post", null=True, 
        related_name='last_post_on')
    stuck = models.BooleanField(default=False)
    locked = models.BooleanField(default=False)
    site = models.ForeignKey(Site, null=False)
    last_read = models.ManyToManyField(User,
        through = 'LastRead',
        related_name='last_read')
    objects = CurrentSiteManager()

    def __unicode__(self):
        return self.subject

    def search_title(self):
        return self.subject

    def search_info(self):
        return None

    @instance_memcache('default-posts-list', 1800)
    def default_post_list(self):
        """ the last ten posts made """

        post_list = self.post_set.select_related('creator').order_by("id")
        post_list = post_list[max(0,post_list.count()-10):]
        return post_list

    @instance_memcache('total-posts', 1800)
    def total_posts(self):
        """ how many posts does a thread have """
        if getattr(self, 'post__count', None):
            return self.post__count
        return self.post_set.count()

    @instance_memcache('total-views', 1800)
    def total_views(self):
        """ how many times has a thread been viewed """

        if getattr(self, 'lastread__read_count__sum', None):
            return self.lastread__read_count__sum
        queryset = LastRead.objects.filter(thread=self)
        agg = queryset.aggregate(models.Sum('read_count'))
        total = agg['read_count__sum']
        if not total:
            return 0
        return total

class Post(models.Model):
    """ a post in a thread """

    thread = models.ForeignKey(Thread, null=False)
    creator = models.ForeignKey(User,null=False)
    body = models.TextField(blank=False)
    bbhash = models.CharField(blank=True, max_length=40)
    created_at = models.DateTimeField('Created at',
        default = datetime.datetime.now, 
        db_index = True)
    posted_from = models.CharField(max_length=1024, blank=True, null=True)

    bbcode = BBCodeField('body', 'bbhash')

    def search_title(self):
        return self.thread.subject

    def search_info(self):
        return self.body

    def get_absolute_url(self):
        return reverse('view-post', args=[self.id])

    def __unicode__(self):
        return "%s: %s"%(str(self.thread),self.body[:20])
    
class LastRead(models.Model):
    """ when did a user last read a thread """
    user = models.ForeignKey(User)
    thread = models.ForeignKey(Thread)
    post = models.ForeignKey(Post, null=True, blank=True)
    timestamp = models.DateTimeField(default = datetime.datetime.now,
        db_index = True)
    read_count = models.IntegerField(default=0)
    
    def post_count(self):
        return Post.objects.filter(thread=self.thread, creator=self.user).count()

class Favorite(models.Model):
    """ Explicitly declare this linking table but mimic the old schema """
    thread = models.ForeignKey(Thread, related_name='favorites')
    user = models.ForeignKey(User)


def update_thread(sender, instance, signal, *args, **kwargs):
    """ a post was made in this thread clear cache appropriately """
    if (instance.thread.last_post_id) is None or (instance.id > instance.thread.last_post_id):

        instance.thread.last_post = instance
        instance.thread.save()

        try:
            lastread = LastRead.objects.get(
                user = instance.creator,
                thread = instance.thread
            )
            lastread.timestamp = instance.created_at
            lastread.post = instance
            lastread.save()
        except LastRead.DoesNotExist:
            lastread = LastRead.objects.create(
                user = instance.creator,
                thread = instance.thread,
                timestamp = instance.created_at,
                post = instance,
            )

def invalidate_front_page(sender, instance, signal, *args, **kwargs):
    """ something has changed on the front page clear cache appropriately """
    cache_key = "thread-list-page:%d:1"%Site.objects.get_current().id
    cache.delete(cache_key)
    del instance.default_post_list
    del instance.total_posts

post_save.connect(update_thread,sender=Post)
post_save.connect(invalidate_front_page,sender=Thread)

arkestrator/board/forms.py
import string
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django import forms
from django.db.models import Q
from arkestrator.board.models import Thread, Post, LastRead
import bbking.errors
import bbking.tags

class ThreadForm(forms.ModelForm):
    """ a form for a new thread must be used with PostForm """
    class Meta:
        model = Thread
        fields = ('subject',)
        widgets = {
            'subject': forms.TextInput(attrs={'size': 70, 'maxlength': 160})
        }

    def clean_subject(self):
        """ remove leading and trailing whitespace from a subject """
        subj = self.cleaned_data["subject"]
        subj = subj.strip(bbking.tags.NON_PRINTING)
        if subj  == '':
            raise forms.ValidationError("whitespace is not a subject")
        return subj

class PostForm(forms.ModelForm):
    """ a form for a new Post """
    class Meta:
        auto_id = False
        model = Post
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'cols': 70, 'rows': 12})
        }

    def clean_body(self):
        naked = self.cleaned_data['body'].strip(bbking.tags.NON_PRINTING)

        if not naked: # lol
            raise forms.ValidationError("This post doesn't say enough.")

        try:
            compiled = bbking.tags.compile(naked)
            if len(compiled) < 1:
                raise forms.ValidationError("This post doesn't say enough.")
        except bbking.errors.CompilationError:
            pass

        return naked

arkestrator/pms/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import PM, Recipient


class NewPMForm(forms.ModelForm):
    """ a form to create a new pm """

    recs = forms.CharField(required=True,
            label="To:", widget=forms.TextInput(attrs={'size': 70}))
    
    class Meta:
        model = PM
        fields = ('recs','subject', 'body')
        widgets = {
            'body': forms.Textarea(attrs={'cols': 70, 'rows': 12}),
            'subject': forms.TextInput(attrs={'size': 70, 'maxlength': 160})
        }
        
    def clean_recs(self):
        """ create a list of users from a string of usernames """

        recipient_list = self.cleaned_data['recs'].split()
        user_list = []
        for rec in recipient_list:
            try:
                user_list.append(User.objects.get(username=rec))
            except User.DoesNotExist:
                raise forms.ValidationError(("User "+ rec +" not found"))
                                            
        self.cleaned_data['recipients_user'] = set(user_list)
        return self.cleaned_data

    def save(self, user):
        pm = PM(
            sender = user,
            subject = self.cleaned_data['subject'],
            body = self.cleaned_data['body']
        )
        pm.save()

        for user in self.cleaned_data['recipients_user']:
            recip = Recipient(recipient=user, message=pm)
            recip.save()
        return pm
        
        
        
        

arkestrator/board/templates/board/get_quote.html
{% load mdctime %}{% autoescape off %}[quote={{ user.username }} posted this on {% mdctime post.created_at long %}] [url=#{{ post.id}}]#{{ post.id }}[/url]
{{ post.body }}[/quote]{% endautoescape %}

arkestrator/board/templates/board/new_pm.html
{% extends "base.html" %}
{% block extrahead %}
<title>New Private Message - {{ site_name }}</title>
{% endblock %}
{% block pagetitle %}
<h1>New thread</h1>
{% endblock %}
{% block content %}
    <form method="post" action="{% url 'new-pm' %}">
        {% csrf_token %}
        <table>
            <tr>
                <th nowrap="nowrap" class="legend"><label for="id_recs">To:</label></th>
                <td>{{ form.recipients }} {{ form.recipients.errors }}</td>
            </tr>
            <tr>
                <th />
                <td class="smallfont">Separate multiple user names with spaces.</td>
            </tr>
            <tr>
                <th nowrap="nowrap" class="legend"><label for="id_subject">Subject:</label></th>
                <td>{{ form.subject }} {{ form.subject.errors }}</td>
            </tr>
            <tr>   
                <th />
                <td>{{ form.body }} {{ form.body.errors }}</td>
            </tr>
            <tr>
                <th />
                <td><input type="submit" value="Send" /></td>
            </tr>
        </table>
    </form>
{% endblock %}

arkestrator/board/templates/board/new_thread.html
{% extends "base.html" %}
{% block extrahead %}
<title>New thread - {{ site_name }}</title>
{% endblock %}
{% block pagetitle %}
<h1>New thread</h1>
{% endblock %}
{% block content %}
<form method="post" action="{% url 'new-thread' %}" onSubmit="document.getElementById('postbutton').style.display='none';" class="replyform">
        {% csrf_token %}
        <table>
            <tr>
                <th nowrap="nowrap" class="legend"><label for="subject">Subject:</label></th>
                <td>{{ thread_form.subject }} {{ thread_form.subject.errors }}</td>
            </tr>
            <tr>
                <th />
                <td>{{ post_form.body }} {{ post_form.body.errors }}</td>
            </tr>
            <tr>
                <th />
                <td><input type="submit" id="postbutton" value="Say It" />
            </td>
        </table>
</form>
{% endblock %}

{% block replyform %}

{% endblock %}

arkestrator/board/templates/board/pm_list.html
{% extends "board/thread_list.html" %}

{% load cache util %}

{% block extramenu %}
    <div id="submenu">
        <ul>
            <li class="submenuitem"><a href="{% url 'new-pm' %}">New PM</a></li>
        </ul>
    </div>
{% endblock extramenu %}

{% block content %}
    <table class="thread_list">
    {% withcycle "row1" "row2" as row_color %}
        {% for thread in thread_list %}
            <tr class="{{ row_color }}">
            <td nowrap="nowrap">
                {% if not thread.other_has_read %}<b>{% endif %}
                <a href="{% url 'view-profile' thread.other_user.id %}">{{ thread.other_user.username }}</a>
                {% if not thread.other_has_read %}</b>{% endif %}
            </td>
            <td nowrap="nowrap" class="icons">{% if thread.locked %}<a href="{% url 'unlock-thread'
                thread.id %}">&#10005;</a>{% endif %}{% if thread.stuck %}<a href="{% url 'unsticky' thread.id %}">&#9733;</a>{% endif %}</td>
            <td class="wwwwwwww">{% if thread.unread %}
                    <b><a href="{% url 'view-thread' thread.id %}{% spaceless %}
                        {% if thread.last_post_read %}
                                #{{ thread.last_post_read }}
                            {% endif %}{% endspaceless %}">
                        {{ thread.subject }}</a></b>
                {% else %}
                    <a href="{% url 'view-thread' thread.id %}{% spaceless %}
                        {% if thread.last_post_read %}
                                #{{ thread.last_post_read }}
                            {% endif %}{% endspaceless %}">
                        {{ thread.subject }}</a>
                {% endif %}
            </td>
            <td nowrap="nowrap">{{ thread.last_post.created_at|date:"h:i a d-M-y"}} <a
                class="smallfont" href="{% url 'view-profile' thread.last_post.creator.id %}">{{ thread.last_post.creator.username }}</a></td>
            <td nowrap="nowrap" class="count">{{ thread.total_posts }}</td>
            <td nowrap="nowrap" class="count"><a href="{% url 'thread-history' thread.id %}">
                {{ thread.total_views }}</a></td>
            </tr>
            {% nextcycle row_color %}
        {% endfor %}
    {% endwithcycle %}
    </table>
{% endblock %}
{% block bottombezel %}
<div id="bottombezel">
    <ul>
            <li class="submenulegend">Page:</li>
    {% for p in page_obj.paginator.page_range %}
        {% if p == page_obj.number %}
            <li class="submenuitem"><a href="?page={{ p }}"><strong>{{ p }}</strong></a></li>
        {% else %}
            <li class="submenuitem"><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
</div>
{% endblock %}

arkestrator/board/templates/board/pm_list2.html
{% extends "board/thread_list.html" %}

{% load cache util %}

{% block extramenu %}
    <div id="submenu">
        <ul>
            <li class="submenuitem"><a href="{% url 'new-pm' %}">New PM</a></li>
        </ul>
    </div>
{% endblock extramenu %}

{% block content %}
    <table class="thread_list">
    {% withcycle "row1" "row2" as row_color %}
        {% for thread in thread_list %}
            <tr class="{{ row_color }}">
            <td nowrap="nowrap">
                {% if not thread.other_has_read %}<b>{% endif %}
                <a href="{% url 'view-profile' thread.other_user.id %}">{{ thread.other_user.username }}</a>
                {% if not thread.other_has_read %}</b>{% endif %}
            </td>
            <td nowrap="nowrap" class="icons">{% if thread.locked %}<a href="{% url 'unlock-thread'
                thread.id %}">&#10005;</a>{% endif %}{% if thread.stuck %}<a href="{% url 'unsticky' thread.id %}">&#9733;</a>{% endif %}</td>
            <td class="wwwwwwww">{% if thread.unread %}
                    <b><a href="{% url 'view-thread' thread.id %}{% spaceless %}
                        {% if thread.last_post_read %}
                                #{{ thread.last_post_read }}
                            {% endif %}{% endspaceless %}">
                        {{ thread.last_post.body }}</a></b>
                {% else %}
                    <a href="{% url 'view-thread' thread.id %}{% spaceless %}
                        {% if thread.last_post_read %}
                                #{{ thread.last_post_read }}
                            {% endif %}{% endspaceless %}">
                        {{ thread.last_post.body }}</a>
                {% endif %}
            </td>
            <td nowrap="nowrap">{{ thread.last_post.created_at|date:"h:i a d-M-y"}} <a
                class="smallfont" href="{% url 'view-profile' thread.last_post.creator.id %}">{{ thread.last_post.creator.username }}</a></td>
            <td nowrap="nowrap" class="count">{{ thread.total_posts }}</td>
            <td nowrap="nowrap" class="count"><a href="{% url 'thread-history' thread.id %}">
                {{ thread.total_views }}</a></td>
            </tr>
            {% nextcycle row_color %}
        {% endfor %}
    {% endwithcycle %}
    </table>
{% endblock %}
{% block bottombezel %}
<div id="bottombezel">
    <ul>
            <li class="submenulegend">Page:</li>
    {% for p in page_obj.paginator.page_range %}
        {% if p == page_obj.number %}
            <li class="submenuitem"><a href="?page={{ p }}"><strong>{{ p }}</strong></a></li>
        {% else %}
            <li class="submenuitem"><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
</div>
{% endblock %}

arkestrator/board/templates/board/pm_post_list.html
{% extends "board/post_list.html" %}

{% block extrahead %}
<script type="text/javascript" language="JavaScript" src="{{ MEDIA_URL }}js/quote.js"></script>
<title>Messages with {{ other_user }} - {{ site_name }}</title>
{% endblock %}

{% block pagetitle %}
    <h1>Messages with {{ other_user }} </h1>
{% endblock %}

{% block extramenu %}
    <div id="submenu">
        <ul>
            {% if not expand %}
                <li class="submenuitem"><a href="{% url 'view-thread-full' thread.id %}">Show all ({{ thread.total_posts }})</a></li>
            {% endif %}
            <li class="submenuitem"><a href="/this/does/nothing/lol">Hide images</a></li>
            <li class="submenuitem"><a href="{% url 'thread-history' thread.id %}">Thread history</a></li>
            <li class="submenuitem"><a href="{% url 'delete-thread' thread.id %}">Delete thread</a></li>
            <li class="submenuitem floatright"><a href="#pagebottom">Jump to bottom</a></li>
        </ul>
    </div>
{% endblock %}

{% load bbking %}
{% block content %}
    {% for post in object_list %}
        <div class="post">
            <a name="{{ post.id }}"></a>
            {% if post.creator == user %}
                <div class="my_post">
            {% else %}
                <div class="row2">
            {% endif %}
                <span id="info_{{ post.id}}"><strong><a href="{% url 'view-profile' post.creator.id %}">{{ post.creator.username }}</a></strong> posted this on {{ post.created_at|date:"D, d-M-Y \a\t h:i:s a"}}</span>
                <strong><a href="javascript:;" onclick="quote('{% url "get-quote" post.id %}')">#{{ post.id }}</a></strong>
                <span class="button"><a href="{% url 'delete-post' post.id %}">Delete</a></span>
            </div>
            <div class="body" id="post_{{ post.id }}">
                <p>{% bbcode post.bbcode %}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block bottombezel %}
    <div id="bottombezel">
        <ul>
            <li class="submenuitem"><a href="{% url 'list-pms' %}">Go back</a></li>
            <li class="submenuitem floatright"><a href="#pagetop">Jump to top</a></li>
        </ul>
    </div>
{% endblock %}
{% block locknotice %}
<div class="notice">{{ other_user.username }} has deleted this thread. You may no longer reply here.</div>
{% endblock %}

arkestrator/board/templates/board/post_include.html
{% load bbking mdctime %}
<div class="post">
<div class="row2">
    <strong>Subject: </strong><a href="{% url 'view-post' object.id %}#{{ object.id }}" title="View post in thread">{{ object.thread.subject }}</a><br/>
    <strong>{{ object.creator }}</strong> posted this at {% mdctime object.created_at long %}
</div>
<div class="body">
    <p>{% bbcode object.bbcode %}</p>
</div>
</div>

arkestrator/board/templates/board/post_list.html
{% extends "base.html" %}

{% load bbking wordfilter %}
{% load mdctime %}

{% block extrahead %}
<script type="text/javascript" language="JavaScript" src="{{ MEDIA_URL }}js/quote.js"></script>
<title>{{ thread.subject|wordfilter}} - {{ site_name }}</title>
{% endblock %}

{% block pagetitle %}
    <h1>{{ thread.subject|wordfilter }} </h1>
{% endblock %}

{% block extramenu %}
        <div id="submenu">
        <ul>
            {% if thread.total_posts > 10 %}
                {% if not expand %}
                    {% if hide %}
                    <li class="submenuitem"><a href="{% url 'view-thread-full-hide' thread.id start %}" title="Show all posts">Show all ({{ thread.total_posts }})</a></li>
                    {% else %}
                    <li class="submenuitem"><a href="{% url 'view-thread-full-start' thread.id start %}" title="Show all posts">Show all ({{ thread.total_posts }})</a></li>
                    {% endif %}
                {% else %}
                    {% if hide %}
                    <li class="submenuitem"><a href="{% url 'view-thread-hide' thread.id start %}" title="Collapse old posts">Collapse</a></li>
                    {% else %}
                    <li class="submenuitem"><a href="{% url 'view-thread-start' thread.id start %}" title="Collapse old posts">Collapse</a></li>
                    {% endif %}
                {% endif %}
            {% endif %}
            {% if hide %}
                {% if expand %}
                    <li class="submenuitem"><a href="{% url 'view-thread-full-show' thread.id start %}" title="Show images">Show Images</a></li>
                {% else %}
                    <li class="submenuitem"><a href="{% url 'view-thread-show' thread.id start %}" title="Show images">Show Images</a></li>
                {% endif %}
            {% else %}
                {% if expand %}
                    <li class="submenuitem"><a href="{% url 'view-thread-full-hide' thread.id start %}" title="Hide images">Hide Images</a></li>
                {% else %}
                    <li class="submenuitem"><a href="{% url 'view-thread-hide' thread.id start %}" title="Hide images">Hide Images</a></li>
                {% endif %}
            {% endif %}
            <li class="submenuitem">
            <form name="fav_form" action="{% url 'favorite' thread.id %}" method="post">
            {% csrf_token %}
            {% if fav %}
                <input type="hidden" name="fav" value="remove">
                <a href="javascript:void(1);" onClick="document.fav_form.submit();" title="Remove from favorites">Unfavorite</a>
            {% else %}
                <input type="hidden" name="fav" value="add">
                <a href="javascript:void(1);" onClick="document.fav_form.submit();" title="Add to favorites">Favorite</a>
            {% endif %}
            </form>
            </li>
            <li class="submenuitem"><a href="{% url 'thread-history' thread.id %}" title="Show thread history">History</a></li>
            {% if perms.board.can_sticky %}
              <li class="submenuitem">
              <form name="stickform" action="{% url 'sticky' thread.id %}" method="post">
              {% csrf_token %}
              {% if thread.stuck %}
                <input type="hidden" name="sticky" value="unsticky">
                <a href="javascript:void(1);" onClick="document.stickform.submit();" title="Unsticky this thread">Unsticky</a>
              {% else %}
                <input type="hidden" name="sticky" value="sticky">
                <a href="javascript:void(1)" onClick="document.stickform.submit();" title="Sticky this thread">Sticky</a></li>
              {% endif %}
              </form>
              </li>
            {% endif %}
            {% if perms.board.can_lock %}
                <li class="submenuitem">
                <form name="lockform" action="{% url 'lock-thread' thread.id %}" method="post">
                {% csrf_token %}
                {% if thread.locked %}
                    <input type="hidden" name="lock" value="unlock">
                    <a href="javascript:void(1)" onClick="document.lockform.submit();" title="Unlock this thread">Unlock</a>
                {% else %}
                    <input type="hidden" name="lock" value="lock">
                    <a href="javascript:void(1)" onClick="document.lockform.submit();" title="Lock this thread">Lock</a>
                {% endif %}
                </form>
                </li>
             {% endif %}
             {% block extrapostmenu %}
             {% endblock %}
            <li class="submenuitem floatright"><a href="#pagebottom" title="Jump to bottom">Jump to bottom</a></li>
        </ul>
    </div>
{% endblock %}
{% block content %}
    {% block prepostcontent %}
    {% endblock %}
    {% for post in object_list %}
        <a name="{{ post.id }}"></a>
        <div class="post">
            {% if post.creator == user %}
                <div class="my_post">
            {% else %}
                <div class="row2">
            {% endif %}
                <strong><a href="{% url 'view-profile' post.creator.id %}" title="View {{ post.creator.username }}'s profile">{{ post.creator.username }}</a></strong> posted this on {% mdctime post.created_at long %}
                <strong><a href="javascript:;" onclick="quote('{% url "get-quote" post.id %}')" title="Quote this post">#{{ post.id }}</a></strong>
            </div>
            <div class="body" id="post_{{ post.id }}">
                <p>{% bbcode post.bbcode %}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}
{% block bottombezel %}
    <div id="bottombezel">
        <ul>
            <li class="submenuitem"><a href="{% url 'list-threads' %}" title="Back to thread list">Go back</a></li>
            <li class="submenuitem floatright" title="jump to top"><a href="#pagetop">Jump to top</a></li>
        </ul>
    </div>
{% endblock %}
{% block replyform %}
{% if not thread.locked %}
<a name="post"></a>
    <form method="post" action="{% url 'view-thread' thread.id %}#post" onSubmit="document.getElementById('postbutton').value='Please wait...';">
    {% csrf_token %}
    <div class="replyform" style="float: left;">
        {{ form.body.errors }}<br />{{ form.body }}<br />
        {{ form.form_lock }}
        <input class="button" type="submit" id="postbutton" value="Say it" />
    </div>
    </form>
{% else %}
{% block locknotice %}
    <div class="notice">This thread is locked. No more replies may be added.</div>
{% endblock %}
{% endif %}
{% endblock %}